# stormpath config
STORMPATH_ENABLE_GIVEN_NAME = False
STORMPATH_ENABLE_MIDDLE_NAME = False
STORMPATH_ENABLE_SURNAME = False
STORMPATH_REDIRECT_URL = '/dashboard'
STORMPATH_ENABLE_REGISTRATION = False
STORMPATH_LOGIN_TEMPLATE = 'account/login.html'
STORMPATH_ENABLE_FORGOT_PASSWORD = True
