"""empty message

Revision ID: 4d438adf1c32
Revises: 294bf8b5ae3c
Create Date: 2015-11-08 21:26:04.714580

"""

# revision identifiers, used by Alembic.
revision = '4d438adf1c32'
down_revision = '294bf8b5ae3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('lead_source', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'lead_source')
    ### end Alembic commands ###
