"""empty message

Revision ID: d85694981ec
Revises: 3c6ad9273b63
Create Date: 2015-10-27 21:53:57.303648

"""

# revision identifiers, used by Alembic.
revision = 'd85694981ec'
down_revision = '3c6ad9273b63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('contacts', 'date_added')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'created_date')
    ### end Alembic commands ###
